class Recipe {
  final String recipeId; // Unique identifier for each recipe
  final String name;
  final String description;
  final String cuisine;
  final String course;
  final String diet;
  final List<String> ingredientsName;
  final List<String> ingredientsQuantity;
  final int prepTime; // in minutes
  final int cookTime; // in minutes
  final String instructions;
  final String imageURL;
  final int totalTime; // in minutes
  final List<String> recipeTags;
  final String difficultyLevel;
  final String ingredientCategory;
  bool isFavorited;

  Recipe({
    required this.recipeId,
    required this.name,
    required this.description,
    required this.cuisine,
    required this.course,
    required this.diet,
    required this.ingredientsName,
    required this.ingredientsQuantity,
    required this.prepTime,
    required this.cookTime,
    required this.instructions,
    required this.imageURL,
    required this.totalTime,
    required this.recipeTags,
    required this.difficultyLevel,
    required this.ingredientCategory,
    this.isFavorited = false,
  });

  factory Recipe.fromJson(Map<String, dynamic> json) {
    return Recipe(
      recipeId: json['recipe_id'] as String,
      name: json['name'] as String,
      description: json['description'] as String,
      cuisine: json['cuisine'] as String,
      course: json['course'] as String,
      diet: json['diet'] as String,
      ingredientsName: List<String>.from(json['ingredients_name']),
      ingredientsQuantity: List<String>.from(json['ingredients_quantity']),
      prepTime: json['prep_time'] as int,
      cookTime: json['cook_time'] as int,
      instructions: json['instructions'] as String,
      imageURL: json['image_url'] as String,
      totalTime: json['total_time'] as int,
      recipeTags: List<String>.from(json['recipe_tags']),
      difficultyLevel: json['difficulty_level'] as String,
      ingredientCategory: json['ingredient_category'] as String,
      isFavorited: json['isFavorited'] as bool? ?? false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'recipe_id': recipeId,
      'name': name,
      'description': description,
      'cuisine': cuisine,
      'course': course,
      'diet': diet,
      'ingredients_name': ingredientsName,
      'ingredients_quantity': ingredientsQuantity,
      'prep_time': prepTime,
      'cook_time': cookTime,
      'instructions': instructions,
      'image_url': imageURL,
      'total_time': totalTime,
      'recipe_tags': recipeTags,
      'difficulty_level': difficultyLevel,
      'ingredient_category': ingredientCategory,
      'isFavorited': isFavorited,
    };
  }

  static List<Recipe> fetchRecipes() {
    return [
      Recipe(
        recipeId: '1',
        name: 'Classic Pancakes',
        description: 'Fluffy and delicious pancakes with syrup and berries.',
        cuisine: 'American',
        course: 'Breakfast',
        diet: 'Vegetarian',
        ingredientsName: ['Flour', 'Eggs', 'Milk', 'Sugar', 'Baking Powder'],
        ingredientsQuantity: ['1 cup', '2', '1 cup', '2 tbsp', '1 tsp'],
        prepTime: 10,
        cookTime: 5,
        instructions: 'Mix ingredients, pour onto griddle, cook until golden brown.',
        imageURL: 'Assets/pancake.jpg',
        totalTime: 15,
        recipeTags: ['Easy', 'Quick'],
        difficultyLevel: 'Easy',
        ingredientCategory: 'Dry Goods',
        isFavorited: true,
      ),

      Recipe(
        recipeId: '2',
        name: 'Garden Salad',
        description: 'Fresh mixed greens with a variety of vegetables.',
        cuisine: 'Mediterranean',
        course: 'Lunch',
        diet: 'Vegan',
        ingredientsName: ['Lettuce', 'Tomato', 'Cucumber', 'Olives'],
        ingredientsQuantity: ['2 cups', '1', '1', '1/4 cup'],
        prepTime: 10,
        cookTime: 0,
        instructions: 'Chop vegetables, mix in a bowl, and serve.',
        imageURL: 'Assets/Ellipse.png',
        totalTime: 10,
        recipeTags: ['Healthy', 'Vegan'],
        difficultyLevel: 'Easy',
        ingredientCategory: 'Vegetables',
        isFavorited: false,
      ),
      Recipe(
        recipeId: '3',
        name: 'Spaghetti Carbonara',
        description: 'A creamy pasta with eggs, cheese, and pancetta.',
        cuisine: 'Italian',
        course: 'Dinner',
        diet: 'Non-Vegetarian',
        ingredientsName: ['Spaghetti', 'Eggs', 'Pancetta', 'Parmesan'],
        ingredientsQuantity: ['200g', '3', '100g', '1/2 cup'],
        prepTime: 10,
        cookTime: 20,
        instructions: 'Cook pasta, mix with egg and cheese, add pancetta.',
        imageURL: 'Assets/Ellipse.png',
        totalTime: 30,
        recipeTags: ['Rich', 'Comfort Food'],
        difficultyLevel: 'Medium',
        ingredientCategory: 'Pasta',
        isFavorited: true,
      ),
      Recipe(
        recipeId: '4',
        name: 'Chicken Caesar Salad',
        description: 'Grilled chicken served with Caesar dressing and crispy lettuce.',
        cuisine: 'American',
        course: 'Lunch',
        diet: 'Non-Vegetarian',
        ingredientsName: ['Chicken Breast', 'Romaine Lettuce', 'Caesar Dressing', 'Croutons'],
        ingredientsQuantity: ['2', '3 cups', '1/4 cup', '1/4 cup'],
        prepTime: 15,
        cookTime: 20,
        instructions: 'Grill chicken, chop lettuce, toss with dressing and croutons.',
        imageURL: 'Assets/Ellipse.png',
        totalTime: 35,
        recipeTags: ['Healthy', 'Grilled'],
        difficultyLevel: 'Medium',
        ingredientCategory: 'Poultry',
        isFavorited: false,
      ),
      Recipe(
        recipeId: '5',
        name: 'Beef Stir Fry',
        description: 'Savory beef with stir-fried vegetables.',
        cuisine: 'Chinese',
        course: 'Dinner',
        diet: 'Non-Vegetarian',
        ingredientsName: ['Beef', 'Bell Peppers', 'Onion', 'Soy Sauce', 'Ginger'],
        ingredientsQuantity: ['200g', '2', '1', '2 tbsp', '1 tsp'],
        prepTime: 10,
        cookTime: 15,
        instructions: 'Stir fry beef and vegetables, add sauce and spices.',
        imageURL: 'Assets/Ellipse.png',
        totalTime: 25,
        recipeTags: ['Savory', 'Quick'],
        difficultyLevel: 'Easy',
        ingredientCategory: 'Meat',
        isFavorited: true,
      ),
      Recipe(
        recipeId: '6',
        name: 'Chocolate Chip Cookies',
        description: 'Soft and chewy cookies loaded with chocolate chips.',
        cuisine: 'American',
        course: 'Dessert',
        diet: 'Vegetarian',
        ingredientsName: ['Flour', 'Butter', 'Sugar', 'Chocolate Chips'],
        ingredientsQuantity: ['2 cups', '1 cup', '1 cup', '1 cup'],
        prepTime: 10,
        cookTime: 12,
        instructions: 'Mix ingredients, drop spoonfuls on baking sheet, bake at 350°F.',
        imageURL: 'Assets/Ellipse.png',
        totalTime: 22,
        recipeTags: ['Sweet', 'Baked'],
        difficultyLevel: 'Easy',
        ingredientCategory: 'Baking',
        isFavorited: true,
      ),
      Recipe(
        recipeId: '7',
        name: 'Chicken Soup',
        description: 'Warm and comforting chicken soup with vegetables.',
        cuisine: 'American',
        course: 'Soup',
        diet: 'Non-Vegetarian',
        ingredientsName: ['Chicken', 'Carrots', 'Celery', 'Onion', 'Chicken Broth'],
        ingredientsQuantity: ['1 lb', '2', '2', '1', '4 cups'],
        prepTime: 15,
        cookTime: 30,
        instructions: 'Cook chicken and vegetables in broth, simmer for 30 minutes.',
        imageURL: 'Assets/Ellipse.png',
        totalTime: 45,
        recipeTags: ['Comforting', 'Hearty'],
        difficultyLevel: 'Medium',
        ingredientCategory: 'Poultry',
        isFavorited: false,
      ),
      Recipe(
        recipeId: '8',
        name: 'Avocado Toast',
        description: 'Toasted bread topped with creamy avocado and spices.',
        cuisine: 'American',
        course: 'Breakfast',
        diet: 'Vegetarian',
        ingredientsName: ['Avocado', 'Bread', 'Olive Oil', 'Chili Flakes'],
        ingredientsQuantity: ['1', '2 slices', '1 tbsp', '1 tsp'],
        prepTime: 5,
        cookTime: 5,
        instructions: 'Toast bread, mash avocado, spread on toast, top with chili flakes.',
        imageURL: 'Assets/Ellipse.png',
        totalTime: 10,
        recipeTags: ['Quick', 'Healthy'],
        difficultyLevel: 'Easy',
        ingredientCategory: 'Fruit',
        isFavorited: true,
      ),
      Recipe(
        recipeId: '9',
        name: 'Grilled Cheese Sandwich',
        description: 'Crispy grilled bread with melted cheese inside.',
        cuisine: 'American',
        course: 'Snack',
        diet: 'Vegetarian',
        ingredientsName: ['Bread', 'Cheese', 'Butter'],
        ingredientsQuantity: ['2 slices', '2 slices', '1 tbsp'],
        prepTime: 5,
        cookTime: 5,
        instructions: 'Butter bread, add cheese, grill until golden brown.',
        imageURL: 'Assets/Ellipse.png',
        totalTime: 10,
        recipeTags: ['Comfort Food', 'Quick'],
        difficultyLevel: 'Easy',
        ingredientCategory: 'Dairy',
        isFavorited: false,
      ),
      Recipe(
        recipeId: '10',
        name: 'Egg Salad',
        description: 'Creamy egg salad made with boiled eggs, mayo, and mustard.',
        cuisine: 'American',
        course: 'Lunch',
        diet: 'Vegetarian',
        ingredientsName: ['Eggs', 'Mayonnaise', 'Mustard', 'Celery'],
        ingredientsQuantity: ['4', '2 tbsp', '1 tsp', '1 stalk'],
        prepTime: 10,
        cookTime: 0,
        instructions: 'Boil eggs, chop and mix with mayo, mustard, and celery.',
        imageURL: 'Assets/Ellipse.png',
        totalTime: 10,
        recipeTags: ['Quick', 'Salad'],
        difficultyLevel: 'Easy',
        ingredientCategory: 'Eggs',
        isFavorited: false,
      ),
      Recipe(
        recipeId: '11',
        name: 'Pineapple Smoothie',
        description: 'Refreshing smoothie made with pineapple, banana, and coconut.',
        cuisine: 'American',
        course: 'Beverage',
        diet: 'Vegan',
        ingredientsName: ['Pineapple', 'Banana', 'Coconut Milk'],
        ingredientsQuantity: ['1 cup', '1', '1/2 cup'],
        prepTime: 5,
        cookTime: 0,
        instructions: 'Blend all ingredients until smooth.',
        imageURL: 'Assets/Ellipse.png',
        totalTime: 5,
        recipeTags: ['Vegan', 'Refreshing'],
        difficultyLevel: 'Easy',
        ingredientCategory: 'Fruit',
        isFavorited: false,
      ),
      Recipe(
        recipeId: '12',
        name: 'Tomato Basil Soup',
        description: 'Rich and creamy soup made with tomatoes and fresh basil.',
        cuisine: 'Italian',
        course: 'Soup',
        diet: 'Vegetarian',
        ingredientsName: ['Tomatoes', 'Basil', 'Cream', 'Garlic'],
        ingredientsQuantity: ['4', '1/4 cup', '1/2 cup', '2 cloves'],
        prepTime: 10,
        cookTime: 20,
        instructions: 'Cook tomatoes and garlic, blend with cream and basil.',
        imageURL: 'Assets/Ellipse.png',
        totalTime: 30,
        recipeTags: ['Comforting', 'Vegetarian'],
        difficultyLevel: 'Medium',
        ingredientCategory: 'Vegetables',
        isFavorited: false,
      ),
      Recipe(
        recipeId: '13',
        name: 'Fish Tacos',
        description: 'Tacos filled with seasoned grilled fish, cabbage, and salsa.',
        cuisine: 'Mexican',
        course: 'Dinner',
        diet: 'Non-Vegetarian',
        ingredientsName: ['Fish', 'Taco Shells', 'Cabbage', 'Salsa'],
        ingredientsQuantity: ['2 fillets', '4', '1 cup', '1/4 cup'],
        prepTime: 10,
        cookTime: 15,
        instructions: 'Grill fish, assemble tacos with cabbage and salsa.',
        imageURL: 'Assets/Ellipse.png',
        totalTime: 25,
        recipeTags: ['Tacos', 'Seafood'],
        difficultyLevel: 'Medium',
        ingredientCategory: 'Seafood',
        isFavorited: true,
      ),

    ];
  }
}
